package com.github.ngnhub.consistent_hash.impl

import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource
import java.math.BigInteger
import kotlin.test.assertEquals

class MmrHashFunctionTest {

    /**
     * Results are compared with the hash generated by the Asecuritysite
     * @see <a href="https://asecuritysite.com/hash/mur">Asecuritysite</a>
     */
    @ParameterizedTest
    @MethodSource("values")
    fun `should return hash according to results from the resource`(values: String, expected: BigInteger) {
        // given
        val mmrHashFunction = MmrHashFunction()

        // when
        val actual = mmrHashFunction.hash(values)

        // then
        assertEquals(actual, expected)
    }

    companion object {
        @JvmStatic
        fun values() = listOf(
            Arguments.of(
                "test value 1",
                BigInteger("318588124588191553894287828696465047533")
            ),
            Arguments.of(
                "test value 2",
                BigInteger("4196214770724666345780832154717773686")
            ),
            Arguments.of(
                "some more specific value",
                BigInteger("298530547240229720053594957485092576065")
            )
        )
    }
}