version: '3.8'
services:
  redis1:
    container_name: redis1
    hostname: redis1
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ../data1:/data
    networks:
      - redis-network

  redis2:
    container_name: redis2
    hostname: redis2
    image: redis:latest
    restart: always
    command: --port '6380'
    ports:
      - '6380:6380'
    volumes:
      - ../dat2:/data
    networks:
      - redis-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    build: .
    environment:
      - REDIS_HOSTS= local:redis1:6379 local:redis2:6380
    ports:
      - "8081:8081"
    networks:
      - redis-network

  redis-coordinator:
    container_name: redis-coordinator
    image: ngnhub/redis-coordinator:latest
    build: .
    ports:
      - "8080:8080"
    networks:
      - redis-network

  server_storage: #todo better ideas?
    container_name: server_storage
    hostname:  server_storage
    image: redis:latest
    restart: always
    command: --port '6300'
    ports:
      - '6300:6300'
    volumes:
      - ../server_storage:/data
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
