version: '3.8'
services:
  redis:
    container_name: redis1
    hostname: redis1
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ../data:/data
    networks:
      - redis-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_HOSTS=local:redis1:6379
    ports:
      - "8081:8081"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
